# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "sensu-lxc-host"
  config.vm.box = 'precise-64-lxc-preseed'
  config.vm.box_url = 'http://vagrant.hw-ops.com/precise-64-lxc-preseed.box'

  if(ENV['ENABLE_APT_PROXY'])
    proxy = [
      "echo \"Acquire::http::Proxy \\\"http://#{ENV['ENABLE_APT_PROXY']}:3142\\\";\" > /etc/apt/apt.conf.d/01proxy",
      "echo \"Acquire::https::Proxy \\\"DIRECT\\\";\" >> /etc/apt/apt.conf.d/01proxy"
    ]
  else
    proxy = []
  end


  config.vm.provision :shell do |shell|
    shell.inline = (
      proxy + [
        "lxc-destroy -n ubuntu_1204",
        "apt-get update",
        "apt-get install -y -q ruby1.9.1-full git",
        "gem install --no-ri --no-rdoc bundler",
        "git clone git://github.com/chrisroberts/vagabond-test-cookbook.git",
        "cd vagabond-test-repo",
        "bundle install --binstubs",
        "bin/vagabond kitchen test --debug",
        "bin/vagabond kitchen test --cluster cacher --debug",
        "cd ..",
        "git clone git://github.com/chrisroberts/vagabond-test-repo.git",
        "cd vagabond-test-repo",
        "bundle install --binstubs",
        "bin/vagabond up test_node --debug",
        "bin/vagabond cluster test_cluster --debug",
        "bin/vagabond cluster test_cluster --parallel --debug",
        "bin/vagabond destroy test_cluster --cluster --debug",
        "bin/vagabond server destroy --debug"
      ]
    ).join("\n")
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
